// ADMIN AUTH
export const API_AUTH_SANCTUM_CSRF_COOKIE = '/sanctum/csrf-cookie'
export const API_AUTH_LOGIN = '/api/login'
export const API_AUTH_LOGOUT = '/api/logout'
export const API_AUTH_USER = '/api/user'

export const API_USERS_RESOURCE = '/api/users'
export const API_NEWS_GROUPS_RESOURCE = '/api/news-groups'
export const API_INFOMATIONS_RESOURCE = '/api/news'
export const API_SETTING_RESOURCE = '/api/settings'

export const API_LINH_MUCS_RESOURCE = '/api/linh-mucs'
export const API_LINH_MUC_BANG_CAPS_RESOURCE = '/api/linh-muc-bang-caps'
export const API_LINH_MUC_CHUC_THANHS_RESOURCE = '/api/linh-muc-chuc-thanhs'
export const API_LINH_MUC_VAN_THUS_RESOURCE = '/api/linh-muc-van-thus'
export const API_LINH_MUC_THUYEN_CHUYENS_RESOURCE =
    '/api/linh-muc-thuyen-chuyens'

export const API_GIAO_PHANS_RESOURCE = '/api/giao-phans'
export const API_GIAO_HATS_RESOURCE = '/api/giao-hats'
export const API_GIAO_XUS_RESOURCE = '/api/giao-xus'
export const API_GIAO_DIEMS_RESOURCE = '/api/giao-diems'
export const API_CONG_DOAN_TU_SIS_RESOURCE = '/api/cong-doan-tu-sis'
export const API_CO_SOS_RESOURCE = '/api/co-sos'
export const API_DONGS_RESOURCE = '/api/dongs'
export const API_THANHS_RESOURCE = '/api/thanhs'
export const API_CHUCVUS_RESOURCE = '/api/chuc-vus'
export const API_LECHINHS_RESOURCE = '/api/le-chinhs'
export const API_DANHMUCS_GIAOPHAN_RESOURCE = '/api/giao-phan/danh-mucs'
export const API_TINTUCS_GIAOPHAN_RESOURCE = '/api/giao-phan/tin-tucs'
export const API_RESTRICT_IPS_RESOURCE = '/api/restrict-ips'
export const API_RESTRICT_IPS_SEARCH_RESOURCE = '/api/search-ips'
export const API_CHANGE_STATUS_IP = '/api/change-status-ips'

export const API_ALBUMS_RESOURCE = '/api/albums'
export const API_ALBUMS_SEARCH_RESOURCE = '/api/search-albums'
export const API_CHANGE_STATUS_ALBUMS = '/api/change-status-albums'

export const API_GROUP_ALBUMS_RESOURCE = '/api/group-albums'
export const API_GROUP_ALBUMS_SEARCH_RESOURCE = '/api/search-group-albums'
export const API_CHANGE_STATUS_GROUP_ALBUMS = '/api/change-status-group-albums'
