export const MODULE_LAYOUT = 'layout'
export const MODULE_DASHBOARD = 'dashboard'
export const MODULE_AUTH = 'auth'
export const MODULE_USER = 'user'
export const MODULE_USER_MODAL = 'user/modal'
export const MODULE_USER_EDIT_MODAL = 'user/editModal'
export const MODULE_INFO = 'info'
export const MODULE_INFO_ADD = 'info/add'
export const MODULE_INFO_EDIT = 'info/edit'
export const MODULE_INFO_MODAL = 'info/modal'
export const MODULE_NEWS_CATEGORY = 'news_category'
export const MODULE_NEWS_CATEGORY_ADD = 'news_category/add'
export const MODULE_NEWS_CATEGORY_EDIT = 'news_category/edit'

export const MODULE_MODULE_APP = 'app_module'
export const MODULE_MODULE_CATEGORY_ICON_SIDE_BAR =
    'app_module/category_icon_side_bar'
export const MODULE_MODULE_CATEGORY_LEFT_SIDE_BAR =
    'app_module/category_left_side_bar'
export const MODULE_MODULE_HOME_BANNER = 'app_module/home_banner'
export const MODULE_MODULE_THONG_BAO = 'app_module/thong_bao'
export const MODULE_MODULE_LOI_CHUA = 'app_module/loi_chua'
export const MODULE_MODULE_TIN_GIAO_HOI_VIET_NAM =
    'app_module/tin_giao_hoi_viet_nam'
export const MODULE_MODULE_TIN_GIAO_HOI = 'app_module/tin_giao_hoi'
export const MODULE_MODULE_TIN_GIAO_PHAN = 'app_module/tin_giao_phan'
export const MODULE_MODULE_VAN_KIEN = 'app_module/van_kien'
export const MODULE_MODULE_NOI_BAT = 'app_module/noi_bat'
export const MODULE_MODULE_SPECIAL_INFO_CAROUSEL =
    'app_module/special_info_carousel'

export const MODULE_MODULE_LINH_MUC = 'linh_muc'
export const MODULE_MODULE_LINH_MUC_ADD = 'linh_muc/add'
export const MODULE_MODULE_LINH_MUC_EDIT = 'linh_muc/edit'
export const MODULE_MODULE_BANG_CAP = 'bang_cap'
export const MODULE_MODULE_BANG_CAP_ADD = 'bang_cap/add'
export const MODULE_MODULE_BANG_CAP_EDIT = 'bang_cap/edit'
export const MODULE_MODULE_CHUC_THANH = 'chuc_thanh'
export const MODULE_MODULE_CHUC_THANH_ADD = 'chuc_thanh/add'
export const MODULE_MODULE_CHUC_THANH_EDIT = 'chuc_thanh/edit'
export const MODULE_MODULE_VAN_THU = 'van_thu'
export const MODULE_MODULE_VAN_THU_ADD = 'van_thu/add'
export const MODULE_MODULE_VAN_THU_EDIT = 'van_thu/edit'
export const MODULE_MODULE_THUYEN_CHUYEN = 'thuyen_chuyen'
export const MODULE_MODULE_THUYEN_CHUYEN_ADD = 'thuyen_chuyen/add'
export const MODULE_MODULE_THUYEN_CHUYEN_EDIT = 'thuyen_chuyen/edit'

export const MODULE_MODULE_GIAO_PHAN = 'giao_phan'
export const MODULE_MODULE_GIAO_PHAN_ADD = 'giao_phan/add'
export const MODULE_MODULE_GIAO_PHAN_EDIT = 'giao_phan/edit'
export const MODULE_MODULE_GIAO_HAT = 'giao_hat'
export const MODULE_MODULE_GIAO_HAT_ADD = 'giao_hat/add'
export const MODULE_MODULE_GIAO_HAT_EDIT = 'giao_hat/edit'
export const MODULE_MODULE_GIAO_XU = 'giao_xu'
export const MODULE_MODULE_GIAO_XU_ADD = 'giao_xu/add'
export const MODULE_MODULE_GIAO_XU_EDIT = 'giao_xu/edit'
export const MODULE_MODULE_GIAO_DIEM = 'giao_diem'
export const MODULE_MODULE_GIAO_DIEM_ADD = 'giao_diem/add'
export const MODULE_MODULE_GIAO_DIEM_EDIT = 'giao_diem/edit'
export const MODULE_MODULE_CONG_DOAN_TU_SI = 'cong_doan_tu_si'
export const MODULE_MODULE_CONG_DOAN_TU_SI_ADD = 'cong_doan_tu_si/add'
export const MODULE_MODULE_CONG_DOAN_TU_SI_EDIT = 'cong_doan_tu_si/edit'
export const MODULE_MODULE_DONG = 'dong'
export const MODULE_MODULE_DONG_ADD = 'dong/add'
export const MODULE_MODULE_DONG_EDIT = 'dong/edit'
export const MODULE_MODULE_CO_SO = 'co_so'
export const MODULE_MODULE_CO_SO_ADD = 'co_so/add'
export const MODULE_MODULE_CO_SO_EDIT = 'co_so/edit'
export const MODULE_MODULE_BAN_CHUYEN_TRACH = 'ban_chuyen_trach'
export const MODULE_MODULE_BAN_CHUYEN_TRACH_ADD = 'ban_chuyen_trach/add'
export const MODULE_MODULE_BAN_CHUYEN_TRACH_EDIT = 'ban_chuyen_trach/edit'
export const MODULE_MODULE_THANH = 'thanh'
export const MODULE_MODULE_THANH_ADD = 'thanh/add'
export const MODULE_MODULE_THANH_EDIT = 'thanh/edit'
export const MODULE_MODULE_CHUC_VU = 'chuc_vu'
export const MODULE_MODULE_CHUC_VU_ADD = 'chuc_vu/add'
export const MODULE_MODULE_CHUC_VU_EDIT = 'chuc_vu/edit'
export const MODULE_MODULE_LE_CHINH = 'le_chinh'
export const MODULE_MODULE_LE_CHINH_ADD = 'le_chinh/add'
export const MODULE_MODULE_LE_CHINH_EDIT = 'le_chinh/edit'
export const MODULE_MODULE_DANHMUC_GIAOPHAN = 'danhmuc_giaophan'
export const MODULE_MODULE_DANHMUC_GIAOPHAN_ADD = 'danhmuc_giaophan/add'
export const MODULE_MODULE_DANHMUC_GIAOPHAN_EDIT = 'danhmuc_giaophan/edit'

export const MODULE_MODULE_TINTUC_GIAOPHAN = 'tintuc_giaophan'
export const MODULE_MODULE_TINTUC_GIAOPHAN_ADD = 'tintuc_giaophan/add'
export const MODULE_MODULE_TINTUC_GIAOPHAN_EDIT = 'tintuc_giaophan/edit'
export const MODULE_MODULE_TINTUC_GIAOPHAN_MODAL = 'tintuc_giaophan/modal'
export const MODULE_TINTUC_GIAOPHAN_MODAL = 'tintuc_giaophan/modal'

export const MODULE_MODULE_RESTRICT_IP = 'restrict_ip'
export const MODULE_MODULE_RESTRICT_IP_ADD = 'restrict_ip/add'
export const MODULE_MODULE_RESTRICT_IP_EDIT = 'restrict_ip/edit'

export const MODULE_MODULE_ALBUMS = 'albums'
export const MODULE_MODULE_ALBUMS_ADD = 'albums/add'
export const MODULE_MODULE_ALBUMS_EDIT = 'albums/edit'
export const MODULE_ALBUMS_MODAL = 'albums/modal'

export const MODULE_MODULE_GROUP_ALBUMS = 'group_albums'
export const MODULE_MODULE_GROUP_ALBUMS_ADD = 'group_albums/add'
export const MODULE_MODULE_GROUP_ALBUMS_EDIT = 'group_albums/edit'
