// APP
export const INIT_LIST = 'INIT_LIST';
export const INIT_INFO_LASTED_LIST = 'INIT_INFO_LASTED_LIST';
export const INIT_INFO_POPULAR_LIST = 'INIT_INFO_POPULAR_LIST';
export const INIT_RELATED_LIST = 'INIT_RELATED_LIST';
export const SET_SUBSCRIBE = 'SET_SUBSCRIBE';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';