export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';

export const LAYOUT_TOGGLE_SIDEBAR = 'LAYOUT_TOGGLE_SIDEBAR';
export const LAYOUT_SWITCH_SIDEBAR = 'LAYOUT_SWITCH_SIDEBAR';
export const LAYOUT_HANDLE_SWIPE = 'LAYOUT_HANDLE_SWIPE';
export const LAYOUT_CHANGE_SIDEBAR_ACTIVE = 'LAYOUT_CHANGE_SIDEBAR_ACTIVE';

export const USERS_SET_LOADING = 'USERS_SET_LOADING';
export const USERS_GET_USER_LIST_SUCCESS = 'USERS_GET_USER_LIST_SUCCESS';
export const USERS_GET_USER_LIST_FAILED = 'USERS_GET_USER_LIST_FAILED';
export const USERS_SET_USER_LIST = 'USERS_SET_USER_LIST';
export const USERS_SET_ERROR = 'USERS_SET_ERROR';
export const USERS_MODAL_SET_OPEN_MODAL = 'USERS_MODAL_SET_OPEN_MODAL'; 
export const USERS_MODAL_SET_CLOSE_MODAL = 'USERS_MODAL_SET_CLOSE_MODAL';
export const USERS_MODAL_SET_IS_OPEN_MODAL = 'USERS_MODAL_SET_IS_OPEN_MODAL';
export const USERS_MODAL_SET_ERROR = 'USERS_MODAL_SET_ERROR';
export const USERS_MODAL_SET_USER_ID = 'USERS_MODAL_SET_USER_ID';
export const USERS_MODAL_SET_USER = 'USERS_MODAL_SET_USER';
export const USERS_MODAL_SET_LOADING = 'USERS_MODAL_SET_LOADING';
export const USERS_MODAL_INSERT_USER_SUCCESS = 'USERS_MODAL_INSERT_USER_SUCCESS';
export const USERS_MODAL_UPDATE_USER_SUCCESS = 'USERS_MODAL_UPDATE_USER_SUCCESS';
export const USERS_MODAL_INSERT_USER_FAILED = 'USERS_MODAL_INSERT_USER_FAILED';
export const USERS_MODAL_UPDATE_USER_FAILED = 'USERS_MODAL_UPDATE_USER_FAILED';

export const NEWS_MODAL_SET_OPEN_MODAL = 'NEWS_MODAL_SET_OPEN_MODAL';
export const NEWS_MODAL_SET_CLOSE_MODAL= 'NEWS_MODAL_SET_CLOSE_MODAL';
export const NEWS_MODAL_SET_IS_OPEN_MODAL= 'NEWS_MODAL_SET_IS_OPEN_MODAL';
export const NEWS_MODAL_SET_NEWS_ID= 'NEWS_MODAL_SET_NEWS_ID';
export const NEWS_MODAL_SET_NEWS = 'NEWS_MODAL_SET_NEWS';
export const NEWS_MODAL_SET_LOADING = 'NEWS_MODAL_SET_LOADING';
export const NEWS_MODAL_INSERT_NEWS_SUCCESS = 'NEWS_MODAL_INSERT_NEWS_SUCCESS';
export const NEWS_MODAL_UPDATE_NEWS_SUCCESS = 'NEWS_MODAL_UPDATE_NEWS_SUCCESS';
export const NEWS_MODAL_INSERT_NEWS_FAILED = 'NEWS_MODAL_INSERT_NEWS_FAILED';
export const NEWS_MODAL_UPDATE_NEWS_FAILED = 'NEWS_MODAL_UPDATE_NEWS_FAILED';
export const NEWS_MODAL_SET_ERROR = 'NEWS_MODAL_SET_ERROR';