export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_USER = 'SET_USER';
export const SET_ERROR = 'SET_ERROR';

export const  USERS_MODAL_SET_OPEN_MODAL = 'USERS_MODAL_SET_OPEN_MODAL'; 
export const  USERS_MODAL_SET_CLOSE_MODAL = 'USERS_MODAL_SET_CLOSE_MODAL';
export const  USERS_MODAL_SET_IS_OPEN_MODAL = 'USERS_MODAL_SET_IS_OPEN_MODAL';
export const  USERS_MODAL_SET_ERROR = 'USERS_MODAL_SET_ERROR';
