export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';

export const USERS_MODAL_SET_OPEN_MODAL = 'USERS_MODAL_SET_OPEN_MODAL'; 
export const USERS_MODAL_SET_CLOSE_MODAL = 'USERS_MODAL_SET_CLOSE_MODAL';
export const USERS_MODAL_SET_IS_OPEN_MODAL = 'USERS_MODAL_SET_IS_OPEN_MODAL';
export const USERS_MODAL_SET_ERROR = 'USERS_MODAL_SET_ERROR';
export const USERS_MODAL_SET_USER_ID = 'USERS_MODAL_SET_USER_ID';
export const USERS_MODAL_SET_USER = 'USERS_MODAL_SET_USER';
export const USERS_MODAL_SET_LOADING = 'USERS_MODAL_SET_LOADING';
export const USERS_MODAL_INSERT_USER_SUCCESS = 'USERS_MODAL_INSERT_USER_SUCCESS';
export const USERS_MODAL_UPDATE_USER_SUCCESS = 'USERS_MODAL_UPDATE_USER_SUCCESS';
export const USERS_MODAL_INSERT_USER_FAILED = 'USERS_MODAL_INSERT_USER_FAILED';
export const USERS_MODAL_UPDATE_USER_FAILED = 'USERS_MODAL_UPDATE_USER_FAILED';